volumes:
  static:

services:
  django_blog:
    build:
      context: .
      dockerfile: docker-compose/production/django/Dockerfile
    image: django_blog
    container_name: django_blog
    working_dir: /app
    volumes:
      - static:/app/static
    env_file:
      - .envs/.production
    ports:
      - "9091:8000"
    command: /start.sh