version: '3'

volumes:
  esdata_local:

services:
  django_blog_local:
    build:
      context: .
      dockerfile: ./docker-compose/local/Dockerfile
    image: django_blog_local
    container_name: django_blog_local
    working_dir: /app
    volumes:
      - .:/app
    env_file:
      - .envs/.production
    ports:
      - "8000:8000"
    command: /start.sh
    depends_on:
      - elasticsearch_local

  elasticsearch_local:
    build:
      context: .
      dockerfile: ./docker-compose/production/elasticsearch/Dockerfile
    image: django_blog_elasticsearch_local
    container_name: django_blog_elasticsearch_local
    volumes:
      - esdata_local:/usr/share/elasticsearch/data
    ports:
      - "9200:9200"
    environment:
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nproc: 65536
      nofile:
        soft: 65536
        hard: 65536