
volumes:
  static:
  database:
  esdata:

services:
  django_blog:
    build:
      context: .
      dockerfile: docker-compose/production/django/Dockerfile
    image: django_blog
    container_name: django_blog
    working_dir: /app
    volumes:
      - database:/app/database
      - static:/app/static
    env_file:
      - .envs/.production
    ports:
      - "8000:8000"
    command: /start.sh
    depends_on:
      - elasticsearch

  nginx:
    build:
      context: .
      dockerfile: docker-compose/production/nginx/Dockerfile
    image: django_blog_nginx
    container_name: django_blog_nginx
    volumes:
      - static:/apps/django_blog/static
    ports:
      - "80:80"
      - "443:443"

  elasticsearch:
    build:
      context: .
      dockerfile: ./docker-compose/production/elasticsearch/Dockerfile
    image: django_blog_elasticsearch
    container_name: django_blog_elasticsearch
    volumes:
      - esdata:/usr/share/elasticsearch/data
    ports:
      - "9200:9200"
    environment:
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nproc: 65536
      nofile:
        soft: 65536
        hard: 65536